<?php

namespace Container4xsZxo9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeance2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wOFu_N7.App\Entity\Seance' shared service.
     *
     * @return \App\Entity\Seance
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wOFu_N7": it references class "App\\Entity\\Seance" but no such service exists.');
    }
}
