<?php

namespace ContainerV7vQUbA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RbfU4YcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RbfU4Yc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RbfU4Yc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'roleuserRepository' => ['privates', 'App\\Repository\\RoleuserRepository', 'getRoleuserRepositoryService', true],
        ], [
            'roleuserRepository' => 'App\\Repository\\RoleuserRepository',
        ]);
    }
}
