<?php

namespace ContainerV7vQUbA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleuserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RfL869e.App\Entity\Roleuser' shared service.
     *
     * @return \App\Entity\Roleuser
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.RfL869e": it references class "App\\Entity\\Roleuser" but no such service exists.');
    }
}
