<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Seance extends \App\Entity\Seance implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'titreSeance', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'descriptionSeance', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'nbParticipantSeance', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'dateDebutSeance', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'dateFinSeance', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'participant', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'coach', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'video'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'titreSeance', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'descriptionSeance', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'nbParticipantSeance', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'dateDebutSeance', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'dateFinSeance', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'participant', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'coach', '' . "\0" . 'App\\Entity\\Seance' . "\0" . 'video'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Seance $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreSeance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreSeance', []);

        return parent::getTitreSeance();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreSeance(string $titreSeance): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreSeance', [$titreSeance]);

        return parent::setTitreSeance($titreSeance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionSeance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionSeance', []);

        return parent::getDescriptionSeance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionSeance(string $descriptionSeance): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionSeance', [$descriptionSeance]);

        return parent::setDescriptionSeance($descriptionSeance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbParticipantSeance(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbParticipantSeance', []);

        return parent::getNbParticipantSeance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbParticipantSeance(int $nbParticipantSeance): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbParticipantSeance', [$nbParticipantSeance]);

        return parent::setNbParticipantSeance($nbParticipantSeance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebutSeance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebutSeance', []);

        return parent::getDateDebutSeance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebutSeance(\DateTimeInterface $dateDebutSeance): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebutSeance', [$dateDebutSeance]);

        return parent::setDateDebutSeance($dateDebutSeance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFinSeance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFinSeance', []);

        return parent::getDateFinSeance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFinSeance(\DateTimeInterface $dateFinSeance): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFinSeance', [$dateFinSeance]);

        return parent::setDateFinSeance($dateFinSeance);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipationSeances(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipationSeances', []);

        return parent::getParticipationSeances();
    }

    /**
     * {@inheritDoc}
     */
    public function addParticipationSeance(\App\Entity\ParticipationSeance $participationSeance): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParticipationSeance', [$participationSeance]);

        return parent::addParticipationSeance($participationSeance);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParticipationSeance(\App\Entity\ParticipationSeance $participationSeance): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParticipationSeance', [$participationSeance]);

        return parent::removeParticipationSeance($participationSeance);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipant(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipant', []);

        return parent::getParticipant();
    }

    /**
     * {@inheritDoc}
     */
    public function addParticipant(\App\Entity\ParticipationSeance $participant): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParticipant', [$participant]);

        return parent::addParticipant($participant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParticipant(\App\Entity\ParticipationSeance $participant): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParticipant', [$participant]);

        return parent::removeParticipant($participant);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoach(): ?\App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoach', []);

        return parent::getCoach();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoach(?\App\Entity\Utilisateur $coach): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoach', [$coach]);

        return parent::setCoach($coach);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberOfParticipationsForUser(\App\Entity\Utilisateur $user): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberOfParticipationsForUser', [$user]);

        return parent::getNumberOfParticipationsForUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function addVideo(\App\Entity\Video $video): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVideo', [$video]);

        return parent::addVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVideo(\App\Entity\Video $video): \App\Entity\Seance
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVideo', [$video]);

        return parent::removeVideo($video);
    }

}
