<?php

namespace ContainerS9655Tn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D96EX5OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d96EX5O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d96EX5O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'roleuser' => ['privates', '.errored..service_locator.d96EX5O.App\\Entity\\Roleuser', NULL, 'Cannot autowire service ".service_locator.d96EX5O": it references class "App\\Entity\\Roleuser" but no such service exists.'],
        ], [
            'roleuser' => 'App\\Entity\\Roleuser',
        ]);
    }
}
