<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPYsMDNC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPYsMDNC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPYsMDNC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPYsMDNC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPYsMDNC\App_KernelDevDebugContainer([
    'container.build_hash' => 'PYsMDNC',
    'container.build_id' => '2ab7c0eb',
    'container.build_time' => 1677369861,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPYsMDNC');
