<?php

namespace ContainerPYsMDNC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__FbOEl0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..fbOEl0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..fbOEl0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participationSeance' => ['privates', '.errored..service_locator..fbOEl0.App\\Entity\\ParticipationSeance', NULL, 'Cannot autowire service ".service_locator..fbOEl0": it references class "App\\Entity\\ParticipationSeance" but no such service exists.'],
            'participationSeanceRepository' => ['privates', 'App\\Repository\\ParticipationSeanceRepository', 'getParticipationSeanceRepositoryService', true],
        ], [
            'participationSeance' => 'App\\Entity\\ParticipationSeance',
            'participationSeanceRepository' => 'App\\Repository\\ParticipationSeanceRepository',
        ]);
    }
}
