<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKqH65LL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKqH65LL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKqH65LL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKqH65LL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKqH65LL\App_KernelDevDebugContainer([
    'container.build_hash' => 'KqH65LL',
    'container.build_id' => '60e830c7',
    'container.build_time' => 1676976272,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKqH65LL');
