<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPy4nx7k\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPy4nx7k/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPy4nx7k.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPy4nx7k\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPy4nx7k\App_KernelDevDebugContainer([
    'container.build_hash' => 'Py4nx7k',
    'container.build_id' => 'e2122e3b',
    'container.build_time' => 1678309281,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPy4nx7k');
