<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS9655Tn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS9655Tn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS9655Tn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS9655Tn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS9655Tn\App_KernelDevDebugContainer([
    'container.build_hash' => 'S9655Tn',
    'container.build_id' => '6b025d36',
    'container.build_time' => 1676914878,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS9655Tn');
