<?php

namespace ContainerWxpaNDu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipationSeance2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1o22mXz.App\Entity\ParticipationSeance' shared service.
     *
     * @return \App\Entity\ParticipationSeance
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1o22mXz": it references class "App\\Entity\\ParticipationSeance" but no such service exists.');
    }
}
