<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHEIKASe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHEIKASe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHEIKASe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHEIKASe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHEIKASe\App_KernelDevDebugContainer([
    'container.build_hash' => 'HEIKASe',
    'container.build_id' => 'e25e2c11',
    'container.build_time' => 1678348780,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHEIKASe');
